### ISSUE TITLE
Register Domains and Assets

### ISSUE THREAD

**Issue by pesterev** [soramitsu/iroha2-longevity-load-rs#31]
First of all, need to cover all register-related instructions. The tool can already register `Account`s, so we need to add `Domain` and `Asset` registration the same way.

New arguments will be available to CLI::
```sh
./longevity-load --accounts 100 --domains 100 --assets 100
```

**Comment by 0x009922** [comment]
> New arguments will be available to CLI::
> 
> ```shell
> ./longevity-load --accounts 100 --domains 100 --assets 100
> ```

This API goes against the design I propsed at #30.

I see the 2 main ways of CLI usage - as a long-running random operations bombing process, and as a single-run process to perform a single operation. This approach make the tool usage very clear. Also I said, that each operation should have its own name, or key.

According to it, there could be a set of operations related to domains/accounts/assets registration. There could be simple ones, like `RegisterDomain`, or maybe more complex like `RegisterDomainAndSeveralAccounts`, or `RegisterAssetAndMintIt`.

For quick start let's create simple operations for registration, such as `RegisterDomain`, `RegisterAccount` and `RegisterAsset` (or maybe `RegisterQuantityAsset`, or `RegisterStoreAsset`, mintable or not etc).

If we need to create a bunch of entities, we should run the tool as a single-operation for each operation. 

I don't know Bash well, but here is an example script in [Nushell](https://www.nushell.sh/book/commands/for.html):

```nu
for $x in 1..100 { 
  ./longevity once --operation RegisterDomain
  ./longevity once --operation RegisterAsset
  ./longevity once --operation RegisterAccount
}
```
