### ISSUE TITLE
Introduce Operation

### ISSUE THREAD

**Issue by pesterev** [soramitsu/iroha2-longevity-load-rs#32]
Seems it needs to introduce a new term called `Operation` to the tool. `Operation` is a combination of instructions that will be executed. Every `Operation` should have a unique key like `RegisterAccount`, `MintOwnAsset` or `TransferAllAssets`. 

I propose to add a set of basic operations first of all: `RegisterAccount`, `RegisterDomain` and `RegisterAsset`.

**Comment by 0x009922** [comment]
> `Operation` is a combination of instructions that will be executed.

I'd like to say that Operation is a scenario, or a use case. It may not only execute instructions (i.e. submit transactions), but also run queries, listen for events etc, i.e. use the whole API provided by Iroha.

Everything else is fine.

**Comment by pesterev** [comment]
> I'd like to say that Operation is a scenario, or a use case. It may not only execute instructions (i.e. submit transactions), but also run queries, listen for events etc, i.e. use the whole API provided by Iroha.

Got it. So it will execute prepared scenarios according to the keys given by a user.
