### ISSUE TITLE
Transfer and Mint Asset

### ISSUE THREAD

**Issue by pesterev** [soramitsu/iroha2-longevity-load-rs#33]
Add new basic `Operation`s that transfer and mint assets.

```
./iroha2_longevity --operation [TransferAsset,MintAsset] --interval 0.2
```

**Comment by 0x009922** [comment]
I don't mind about `TransferAsset` and `MintAsset` operations, but I do so about the CLI sample.

If you mean to run the long-running process that only performs some specified operations, I'd like to invoke it as this:

```bash
./longevity long-running --interval 0.2 --only-operation MintAsset --only-operation TransferAsset
```

Here it is clear [for me] that:

- it a long-running process
- all other operations except of specified are filtered out
