### ISSUE TITLE
A `Vec<String>` tells the reader very little about what's actually going to happen. I'd recommend adding types for each variant and making it an `enum`.

### ISSUE THREAD

**Issue by appetrosyan** [soramitsu/iroha2-longevity-load-rs#42]
A `Vec<String>` tells the reader very little about what's actually going to happen. I'd recommend adding types for each variant and making it an `enum`.

_Originally posted by @appetrosyan in https://github.com/soramitsu/iroha2-longevity-load-rs/pull/35#discussion_r971622847_

**Comment by pesterev** [comment]
It closed at #35
